// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiM9olcQLJOiAXH5EltirLmFOpR51lBiw',
    appId: '1:2471544090:web:2661c0461d7705d71418a3',
    messagingSenderId: '2471544090',
    projectId: 'testing-1c9c2',
    authDomain: 'testing-1c9c2.firebaseapp.com',
    storageBucket: 'testing-1c9c2.appspot.com',
    measurementId: 'G-Z81S9TFGLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxpVj5RS8I3lkgWfcI3UEYZPXUjtFm6lw',
    appId: '1:2471544090:android:14392be3b582ef471418a3',
    messagingSenderId: '2471544090',
    projectId: 'testing-1c9c2',
    storageBucket: 'testing-1c9c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcWjHmXA9gLzo3R1NdGqmSFOJ9hW-hdY',
    appId: '1:2471544090:ios:65e20b30b8d2719f1418a3',
    messagingSenderId: '2471544090',
    projectId: 'testing-1c9c2',
    storageBucket: 'testing-1c9c2.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDcWjHmXA9gLzo3R1NdGqmSFOJ9hW-hdY',
    appId: '1:2471544090:ios:65e20b30b8d2719f1418a3',
    messagingSenderId: '2471544090',
    projectId: 'testing-1c9c2',
    storageBucket: 'testing-1c9c2.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );
}
